services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: api_dex
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - .:/var/www
    command: >
      bash -c "a2ensite 000-default && apache2ctl -D FOREGROUND"
